MvcSozluk/MvcSozluk/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Compilation;
using System.Web.Mvc;

namespace MvcSozluk.Controllers
{
    public class WriterController : Controller
    {
        // GET: Writer
        WriterValidator writerValidator = new WriterValidator();
        WriterManager vm = new WriterManager(new EfWriterDal());
        public ActionResult Index()
        {
            var WriterValues=vm.GetList();
            return View(WriterValues);
        }
        [HttpGet]
        public ActionResult AddWriter()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddWriter(Writer p)
        {
            ValidationResult results= writerValidator.Validate(p);
            if (results.IsValid)
            {
                vm.WriterAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult EditWriter(int id)
        {
            var writervalue = vm.GetByID(id);
            return View(writervalue);
        }
        [HttpPost]
        public ActionResult EditWriter(Writer p)
        {
            ValidationResult results = writerValidator.Validate(p);
            if (results.IsValid)
            {
                vm.WriterUpdate(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();
        }
    }
}

MvcSozluk/MvcSozluk/Views/Writer/AddWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "AddWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Yazar Ekleme</h2>
<br />
@using (Html.BeginForm("AddWriter", "Writer", FormMethod.Post))
            {
<div class="form-group">
    @Html.Label("Yazar Adı")
    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterName)
    <br />
    @Html.Label("Yazar Soyadı")
    @Html.TextBoxFor(x => x.WriteSurName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriteSurName)
    <br />
    @Html.Label("Yazar Mail")
    @Html.TextBoxFor(x => x.WriteMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriteMail)
    <br />
    @Html.Label("Yazar Şifresi")
    @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterPassword)
    <br />
    @Html.Label("Yazar Görsel Linki")
    @Html.TextBoxFor(x => x.WriteImage, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriteImage)
    <br />
    @Html.Label("Yazar Ünvan")
    @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterTitle)
    <br />
    @Html.Label("Yazar Hakkında")
    @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterAbout)
    <br />
    <button class="btn btn-info">Yazarı Ekle</button>
</div>
            }

MvcSozluk/MvcSozluk/Views/Writer/EditWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "EditWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yazar Düzenleme Sayfası</h2>
@using (Html.BeginForm("EditWriter", "Writer", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.Label("Yazar ID")
                    @Html.TextBoxFor(x => x.WriterID, new { @class = "form-control" })
                    <br />
                    @Html.Label("Yazar Adı")
                    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriterName)
                    <br />
                    @Html.Label("Yazar Soyadı")
                    @Html.TextBoxFor(x => x.WriteSurName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriteSurName)
                    <br />
                    @Html.Label("Yazar Mail")
                    @Html.TextBoxFor(x => x.WriteMail, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriteMail)
                    <br />
                    @Html.Label("Yazar Şifresi")
                    @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriterPassword)
                    <br />
                    @Html.Label("Yazar Görsel Linki")
                    @Html.TextBoxFor(x => x.WriteImage, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriteImage)
                    <br />
                    @Html.Label("Yazar Ünvanı")
                    @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriterTitle)
                    <br />
                    @Html.Label("Yazar Hakkında")
                    @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriterAbout)
                    <br />
                    <button class="btn btn-success">Değişiklikleri Uygula</button>
                </div>
            }

MvcSozluk/MvcSozluk/Views/Writer/Index.cshtml
@using EntityLayer.Concrete
@model List<Writer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yazarlar Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                    @item.WriterTitle
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.WriterName @item.WriteSurName</b></h2>
                                            <p class="text-muted text-sm"><b>About: </b>@item.WriterAbout. </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Mail:@item.WriteMail</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="~/AdminLTE-3.0.4/dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="#" class="btn btn-sm bg-teal">
                                            <i class="fas fa-comments">Yazarın Başlıkları</i>
                                        </a>
                                        <a href="/Writer/EditWriter/@item.WriterID" class="btn btn-sm btn-primary">
                                            <i class="fas fa-user"></i> Proili Düzenlle
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</body>
</html>