MvcSozluk/MvcSozluk/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcSozluk.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        [Authorize(Roles="B")]
        public ActionResult Index()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryvalidator = new CategoryValidator();
            ValidationResult result = categoryvalidator.Validate(p);
            if (result.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryvalue=cm.GetByID(id);
            cm.CategoryDelete(categoryvalue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditCategory(int id) 
        {
            var categoryvalue=cm.GetByID(id);
            return View(categoryvalue);
        }

        [HttpPost]
        public ActionResult EditCategory(Category p)
        {
           cm.CategoryUpdate(p);
           return RedirectToAction("Index");   
        }
    }
}

MvcSozluk/MvcSozluk/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h1>Yeni Kategori Ekle</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post)) //birinic değer üzerinde calıştığım action, model ismi ve form metodunun değeri (post etmek istediğimiz için)
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new {@class="form-control"})
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /> <br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /> <br />
        <button class="btn btn-info">Ekle</button>
    </div>
}

MvcSozluk/MvcSozluk/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kategori Güncelleme Sayfası</h2>

@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori ID")
        @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

MvcSozluk/MvcSozluk/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <br />
    <tr>

        <th>#</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>

    </tr>
    @foreach (var item in Model)
    {

        <tr>
            <th>@item.CategoryID </th>
            <td>@item.CategoryName </td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">Sil</td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-warning">Güncelle</td>
            <td><a href="#" class="btn btn-primary">Başlıklar</td>
        </tr>

    }

</table>
<br />
<a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>